export const CONSTANTS = {
  APP_NAME: "HireVora",
  APP_VERSION: "1.0.0",

  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX_REQUESTS: 100,

  USER_ROLES: {
    CANDIDATE: "CANDIDATE",
    RECRUITER: "RECRUITER",
    ADMIN: "ADMIN",
  },

  APPLICATION_STATUSES: {
    APPLIED: "APPLIED",
    SCREENING: "SCREENING",
    SHORTLISTED: "SHORTLISTED",
    INTERVIEW: "INTERVIEW",
    OFFER: "OFFER",
    HIRED: "HIRED",
    REJECTED: "REJECTED",
  },
} as const;